# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 479334b13e47cc26e5dfd7e61711ad099a2b34effc591953dd9ae8b80a0502800a969c9bc45ffc5a64c490854055a86198e837f7718beba1b8ee67c2a468f58f

test:
  secret_key_base: b72d4d9a8377786eeaf215072b4405595451fc8e9abcacbf7bc491a7ff29fc10b948ebabbdfc43407ddcafe52366d4e73f126e79acfcf58351dc29d39937a90f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
